AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an IAM role for CloudFormation Git sync

Resources:
  CloudFormationSyncRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudformation-git-sync-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Policies:
        - PolicyName: CloudFormationGitSyncPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:PassRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - arn:aws:s3:::amrthabit.com
                  - arn:aws:s3:::amrthabit.com/*
              - Effect: Allow
                Action:
                  - cloudfront:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource: '*'

Outputs:
  RoleARN:
    Description: ARN of the CloudFormation sync role
    Value: !GetAtt CloudFormationSyncRole.Arn